postMerge :
  subModules:    
      - name: jest-babel
        preRun:
          command:
            - pnpm install
            - pnpm run -r clean
            - pnpm run -r build
        path : "./examples/jest-babel/"
        pattern: 
          - "./test/index.spec.ts"
        framework : jest
        configFile : "./babel.config.js"
version : 2.0.0
nodeVersion: 16.15.0
tier: large
